admin/src/web/controllers/pago.py
from datetime import datetime
from flask import flash, redirect, render_template, request, url_for
from flask import session, abort
from core import equipo, pago
from flask import Blueprint
from web.helpers.auth import check_permission, is_authenticated

bprint = Blueprint("pago", __name__, url_prefix="/pago")


@bprint.get("/")
def index():
    """Página principal que muestra la lista de pagos con paginación, filtro por fechas y tipos de pago."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_index"):
        return abort(403)
    amount_per_page = 10
    try:
        page = int(request.args.get("pag", "1"))
        order = request.args.get("order", "desc")
        tipos = request.args.getlist("tipopago")

        fecha_min = request.args.get("fechamin", "")

        if fecha_min:
            fecha_min = fecha_min.split(" ")[0]
            fecha_min = datetime.strptime(fecha_min, "%Y-%m-%d")
        else:
            fecha_min = datetime.min

        fecha_max = request.args.get("fechamax", "")
        if fecha_max:
            fecha_max = fecha_max.split(" ")[0]
            fecha_max = datetime.strptime(fecha_max, "%Y-%m-%d")
        else:
            fecha_max = datetime.max

        pagos = pago.list_pagos_page(
            amount_per_page, page, fecha_min, fecha_max, tipos, order
        )
        total = pago.get_total(fecha_min, fecha_max, tipos)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect("/")

    return render_template(
        "pago/index.html",
        pagos=pagos,
        pag=page,
        page_amount=(total + amount_per_page - 1) // amount_per_page,
        tipos=tipos,
        fecha_min=("" if fecha_min == datetime.min else fecha_min),
        fecha_max=("" if fecha_max == datetime.max else fecha_max),
        order=order,
    )


@bprint.get("/<id>")
def get_info(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_get_info"):
        return abort(403)
    """Muestra la información detallada de un pago específico."""
    try:
        chosen_pago = pago.get_one(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.index"))

    return render_template("pago/pago_info.html", info=chosen_pago)


@bprint.get("<id>/edit")
def enter_edit(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_enter_edit"):
        return abort(403)
    """Permite editar un pago existente, cargando los datos actuales del pago."""
    try:
        chosen_pago = pago.get_one(id)

        amount_per_page = 5

        page = int(request.args.get("pag", "1"))

        desc = request.args.get("desc", chosen_pago.desc)
        monto = request.args.get("monto", chosen_pago.monto)
        fecha = request.args.get("fecha", chosen_pago.fecha.strftime("%Y-%m-%d"))
        tipo = request.args.get("tipo", chosen_pago.tipo)

        empleados = equipo.list_equipos_page(page=page, amount_per_page=amount_per_page)
        total_empleados = equipo.get_total()
        page_amount = (total_empleados + amount_per_page - 1) // amount_per_page
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.get_one", id=id))

    return render_template(
        "pago/pago_editing.html",
        info=chosen_pago,
        empleados=empleados,
        pag=page,
        page_amount=page_amount,
        desc=desc,
        monto=monto,
        fecha=fecha,
        tipo=tipo,
    )


@bprint.post("<id>/edit")
def save_edit(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_save_edit"):
        return abort(403)
    """Guarda los cambios realizados a un pago existente."""
    try:
        new_data = {
            "desc": request.form["desc"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "tipo": request.form["tipo"],
        }

        edited_pago = pago.edit(id, new_data)

        if new_data["tipo"] == "Honorario":
            try:
                new_person_id = request.form["chosen-beneficiario"]
            except:
                flash("No se seleccionó un beneficiario", "danger")
                return redirect(url_for("pago.enter_edit", id=id))
            new_person = equipo.get_one(new_person_id)
            pago.assign_pago(new_person, edited_pago)
        else:
            if edited_pago.beneficiario_id:
                pago.unassign_pago(edited_pago)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("pago/pago_info.html", info=edited_pago)


@bprint.post("/<id>/borrar")
def delete(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_delete"):
        return abort(403)
    """Elimina un pago por su ID."""
    try:
        pago.delete_pago(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("get_info", id=id))

    flash("Pago borrado con éxito", "success")
    return redirect(url_for("pago.index"))


@bprint.get("/agregar")
def enter_add():
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_enter_add"):
        return abort(403)
    """Permite agregar un nuevo pago, mostrando un formulario para ingresar los datos."""
    amount_per_page = 5

    page = int(request.args.get("pag", "1"))
    empleados = equipo.list_equipos_page(page=page, amount_per_page=amount_per_page)
    total_empleados = equipo.get_total()
    page_amount = (total_empleados + amount_per_page - 1) // amount_per_page

    desc = request.args.get("desc", "")
    monto = request.args.get("monto", "")
    fecha = request.args.get("fecha", "")
    tipo = request.args.get("tipo", "")

    return render_template(
        "pago/pago_adding.html",
        empleados=empleados,
        pag=page,
        page_amount=page_amount,
        other_page=(True if page > 1 else False),
        desc=desc,
        monto=monto,
        fecha=fecha,
        tipo=tipo,
    )


@bprint.post("/agregar")
def add():
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_add"):
        return abort(403)
    """Crea un nuevo pago basado en los datos ingresados en el formulario."""
    try:
        new_data = {
            "desc": request.form["desc"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "tipo": request.form["tipo"],
        }

        new_pago = pago.create_pago(**new_data)

        if new_data["tipo"] == "Honorario":
            try:
                new_person_id = request.form["chosen-beneficiario"]
            except:
                flash("No se seleccionó un beneficiario", "danger")
                return redirect(url_for("pago.enter_edit", id=id))
            new_person = equipo.get_one(new_person_id)
            pago.assign_pago(new_person, new_pago)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("pago/pago_info.html", info=new_pago)

admin/src/web/templates/pago/index.html
{% extends "layout.html" %} {% block title %} Pagos {% endblock %} {% block head
%} {{ super() }} {% endblock %} {% block content %}
<main role="main" class="container">
  {% include "pago/components/messages.html" %}
  <div class="content-body">
    <!-- TITULO -->
    <div class="row align-items-center justify-content-start">
      <div class="col-auto">
        <h1>Pagos</h1>
      </div>
    </div>

    <!-- BARRA DE BUSQUEDA -->
    {% include 'pago/components/pago_searchbar.html'%}

    <!-- TABLA CON ELEMENTOS-->
    {% if page_amount > 0 %} {% include "pago/components/pago_table.html" %}
    <!-- TABLA SIN ELEMENTOS -->
    {% else %}
    <div class="row container text-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-clipboard-minus"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M5.5 9.5A.5.5 0 0 1 6 9h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"
        />
        <path
          d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"
        />
        <path
          d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"
        />
      </svg>
      <h4>No se encontraron pagos</h4>
    </div>
    {% endif %}
  </div>
</main>
{% endblock %}

admin/src/web/templates/pago/pago_adding.html
{% extends "layout.html" %} {% block title %} Lista de empleados {% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container">
  {% include "pago/components/messages.html" %}
  <form
    id="add-form"
    class="needs-validation"
    novalidate
    action="{{url_for('pago.add')}}"
    method="POST"
  >
    <div class="row">
        <div class="col">
          <div class="row mb-5">
            <h2 class="equipo-profile-title text-secondary">
              Descripción
            </h2>
            <div class="input-group">
              <textarea id="desc-id" class="form-control" name="desc" aria-label="With textarea" required>{{ desc }}</textarea>
              <div class="invalid-feedback">
                Ingrese una descripción.
              </div>
            </div>
          </div>
          <div class="row">
            <h2 class="equipo-profile-title text-secondary">Datos</h2>
            <ul class="list-unstyled mb-1-9">
              <li class="mb-2 mb-xl-3 display-28">
                  <span class="display-26 text-primary me-2 font-weight-600"
                    >Monto:</span
                  >
                  <div class="input-group">
                      <span class="input-group-text" id="basic-addon1">$</span>
                      <input value="{{ monto }}" id="monto-id" name="monto" class="form-control" required pattern="^(?!0+(\.0+)?$)(\d{1,10}(\.\d{1,2})?)$">
                      <div class="invalid-feedback">
                        Ingrese un monto.
                      </div>
                  </div>
                </li>
                <li class="mb-2 mb-xl-3 display-28">
                  <span class="display-26 text-primary me-2 font-weight-600"
                    >Fecha de pago:</span
                  >
                  <input value="{{fecha}}" type="date" id="fecha-id" name="fecha" class="form-control" required>
                  <div class="invalid-feedback">
                    Ingrese una fecha.
                  </div>
                </li>
                <li class="mb-2 mb-xl-3 display-28">
                  <span class="display-26 text-primary me-2 font-weight-600"
                    >Tipo de pago:</span
                  >
                  <select id="tipo-id" name="tipo" class="form-control" required>
                      <option {%if tipo == ''%}selected{%endif%} hidden disabled value=""></option>
                      <option {%if tipo == 'Proveedor'%}selected{%endif%} value="Proveedor">Proveedor</option>
                      <option {%if tipo == 'Gastos varios'%}selected{%endif%} value="Gastos varios">Gastos varios</option>
                      <option {%if tipo == 'Honorario'%}selected{%endif%} value="Honorario">Honorario</option>
                  </select>
                  <div class="invalid-feedback">
                    Seleccione un tipo de pago.
                  </div>
                </li>
            </ul>
          </div>
          
          <div class="row" id="beneficiario-container">
              <div class="col">
                <h2 class="equipo-profile-title text-secondary">Beneficiario</h2>
              </div>
              <div class="col-auto">
                {%include 'pago/components/pago_pagination_add.html'%}
              </div>
              <ul class="list-group list-unstyled container">
                  {%for persona in empleados%}
                  <div class="d-flex align-items-center">
                    <input value="{{persona.id}}" class="" type="radio" name="chosen-beneficiario" id="radio-{{persona.id}}">
                    <label class="form-control ms-2" for="radio-{{persona.id}}">
                      {{persona.nombre}} {{persona.apellido}}
                    </label>
                  </div>
                  {%endfor%}
              </ul>
          </div>
          
        </div>
        <div class="col-4 d-flex justify-content-end align-items-start">
          <button
            class="btn btn-outline-primary mx-2 align-self-start"
            type="submit"
          >
            Guardar
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy" viewBox="0 0 16 16">
              <path d="M11 2H9v3h2z"/>
              <path d="M1.5 0h11.586a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13A1.5 1.5 0 0 1 1.5 0M1 1.5v13a.5.5 0 0 0 .5.5H2v-4.5A1.5 1.5 0 0 1 3.5 9h9a1.5 1.5 0 0 1 1.5 1.5V15h.5a.5.5 0 0 0 .5-.5V2.914a.5.5 0 0 0-.146-.353l-1.415-1.415A.5.5 0 0 0 13.086 1H13v4.5A1.5 1.5 0 0 1 11.5 7h-7A1.5 1.5 0 0 1 3 5.5V1H1.5a.5.5 0 0 0-.5.5m3 4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V1H4zM3 15h10v-4.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5z"/>
            </svg>
          </button>
          <a class="btn btn-outline-secondary mx-2 align-self-start" onclick=window.location.href="{{ url_for('pago.index') }}";>
            Cancelar
          </a>
        </div>
      </div>
  </form>
</div>

<script>
  function toggleBeneficiario() {
    const tipoPago = document.querySelector('select[name="tipo"]');
    const beneficiarioContainer = document.getElementById('beneficiario-container');

    // Mostrar u ocultar el contenedor basado en la opción seleccionada
    tipoPago.addEventListener('change', function() {
      if (tipoPago.value === 'Honorario') {
        beneficiarioContainer.style.display = 'block';  // Mostrar el componente
      } else {
        beneficiarioContainer.style.display = 'none';   // Ocultar el componente
      }
    });

    // Ejecutar al cargar la página para configurar la visibilidad inicial
    if (tipoPago.value === 'Honorario') {
      beneficiarioContainer.style.display = 'block';
    } else {
      beneficiarioContainer.style.display = 'none';
    }
  }

  toggleBeneficiario();



  function validateForm(){
    'use strict'

    const form = document.getElementById("add-form")
    const tipoPago = document.querySelector('select[name="tipo"]');
    const beneficiarios = document.querySelectorAll('input[name="chosen-beneficiario"]');
    let beneficiarioSeleccionado = false;

  
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }


      if (tipoPago.value === 'Honorario') {
        // Comprobar si algún beneficiario está seleccionado
        beneficiarios.forEach(beneficiario => {
          if (beneficiario.checked) {
            beneficiarioSeleccionado = true;
          }
        });

        // Si no hay ningún beneficiario seleccionado, mostrar mensaje y evitar el envío del formulario
        if (!beneficiarioSeleccionado) {
          event.preventDefault();
          event.stopPropagation();

          // Mostrar mensaje de error
          const beneficiarioContainer = document.getElementById('beneficiario-container');
          let errorMsg = beneficiarioContainer.querySelector('.error-message');
          if (!errorMsg) {
            errorMsg = document.createElement('div');
            errorMsg.classList.add('invalid-feedback', 'd-block', 'error-message');
            errorMsg.innerText = 'Debe seleccionar un beneficiario.';
            beneficiarioContainer.appendChild(errorMsg);
          }

          beneficiarios.forEach(beneficiario => {
            beneficiario.classList.add('is-invalid');
            beneficiario.classList.remove('is-valid');
          });
        } else {
          beneficiarios.forEach(beneficiario => {
            beneficiario.classList.remove('is-invalid');
            // Aquí removemos la clase 'is-valid' manualmente para evitar que se aplique el verde
            beneficiario.classList.remove('is-valid');
          });

        }
      }
    

      form.classList.add('was-validated')
    }, false)

    
  }

  validateForm();
  

</script>

{% endblock %}

admin/src/web/templates/pago/pago_editing.html
{% extends "layout.html" %} {% block title %} Lista de empleados {% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container">
  {% include "pago/components/messages.html" %}
  <form
    id="edit-form"
    class="needs-validation"
    novalidate
    action="{{url_for('pago.save_edit', id=info.id)}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="row">
      <div class="col">
        <div class="row mb-5">
          <h2 class="equipo-profile-title text-secondary">
            Descripción
          </h2>
          <div class="input-group">
            <textarea class="form-control" name="desc" id="desc-id" aria-label="With textarea" required>{{desc}}</textarea>
            <div class="invalid-feedback">
              Ingrese una descripción.
            </div>
          </div>
        </div>
        <div class="row">
          <h2 class="equipo-profile-title text-secondary">Datos</h2>
          <ul class="list-unstyled mb-1-9">
            <li class="mb-2 mb-xl-3 display-28">
                <span class="display-26 text-primary me-2 font-weight-600"
                  >Monto:</span
                >
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon1">$</span>
                    <input name="monto" id="monto-id" class="form-control" value="{{ monto }}" required pattern="^(?!0+(\.0+)?$)(\d{1,10}(\.\d{1,2})?)$">
                    <div class="invalid-feedback">
                      Ingrese un monto.
                    </div>
                </div>
              </li>
              <li class="mb-2 mb-xl-3 display-28">
                <span class="display-26 text-primary me-2 font-weight-600"
                  >Fecha de pago:</span
                >
                <input type="date" name="fecha" id="fecha-id" class="form-control" value="{{ fecha }}" required>
                <div class="invalid-feedback">
                  Ingrese una fecha.
                </div>
              </li>
              <li class="mb-2 mb-xl-3 display-28">
                <span class="display-26 text-primary me-2 font-weight-600"
                  >Tipo de pago:</span
                >
                <select id="tipo-id" name="tipo" class="form-control">
                    <option  value="Proveedor" {% if tipo == 'Proveedor' %}selected{% endif %}>Proveedor</option>
                    <option value="Gastos varios" {% if tipo == 'Gastos varios' %}selected{% endif %}>Gastos varios</option>
                    <option value="Honorario" {% if tipo == 'Honorario' %}selected{% endif %}>Honorario</option>
                </select>
              </li>
          </ul>
        </div>
        
        <div class="row" id="beneficiario-container">
            <div class="col">
              <h2 class="equipo-profile-title text-secondary">Beneficiario</h2>
            </div>
            <div class="col-auto">
              {%include 'pago/components/pago_pagination_edit.html'%}
            </div>
            <ul class="list-group list-unstyled container">
                {%for persona in empleados%}
                <div class="form-check d-flex align-items-center">
                  <input value="{{persona.id}}" {%if info.beneficiario.id == persona.id %}checked {%endif%} class="form-check-input" type="radio" name="chosen-beneficiario" id="radio-{{persona.id}}">
                  <label class="form-check-label form-control ms-2" for="radio-{{persona.id}}">
                    {{persona.nombre}} {{persona.apellido}}
                  </label>
                </div>
                {%endfor%}
            </ul>
        </div>
        
      </div>
      <div class="col-4 d-flex justify-content-end align-items-start">
        <button
          class="btn btn-outline-primary mx-2 align-self-start"
          type="submit"
        >
          Guardar
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy" viewBox="0 0 16 16">
            <path d="M11 2H9v3h2z"/>
            <path d="M1.5 0h11.586a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13A1.5 1.5 0 0 1 1.5 0M1 1.5v13a.5.5 0 0 0 .5.5H2v-4.5A1.5 1.5 0 0 1 3.5 9h9a1.5 1.5 0 0 1 1.5 1.5V15h.5a.5.5 0 0 0 .5-.5V2.914a.5.5 0 0 0-.146-.353l-1.415-1.415A.5.5 0 0 0 13.086 1H13v4.5A1.5 1.5 0 0 1 11.5 7h-7A1.5 1.5 0 0 1 3 5.5V1H1.5a.5.5 0 0 0-.5.5m3 4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V1H4zM3 15h10v-4.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5z"/>
          </svg>
        </button>
        <a class="btn btn-outline-secondary mx-2 align-self-start" onclick=window.location.href="{{ url_for('pago.get_info', id=info.id) }}";>
          Cancelar
        </a>
      </div>
    </div>
  </form>
</div>

<script>
  function toggleBeneficiario() {
    const tipoPago = document.querySelector('select[name="tipo"]');
    const beneficiarioContainer = document.getElementById('beneficiario-container');

    // Mostrar u ocultar el contenedor basado en la opción seleccionada
    tipoPago.addEventListener('change', function() {
      if (tipoPago.value === 'Honorario') {
        beneficiarioContainer.style.display = 'block';  // Mostrar el componente
      } else {
        beneficiarioContainer.style.display = 'none';   // Ocultar el componente
      }
    });

    // Ejecutar al cargar la página para configurar la visibilidad inicial
    if (tipoPago.value === 'Honorario') {
      beneficiarioContainer.style.display = 'block';
    } else {
      beneficiarioContainer.style.display = 'none';
    }
  }

  toggleBeneficiario();



  function validateForm(){
    'use strict'

    const form = document.getElementById("edit-form")
  
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)

    
  }

  validateForm();
  function eliminarArchivo(archivo_id){
      const field = document.getElementById(`archivo-field-${archivo_id}`);
      const checker = document.getElementById(`input-check-${archivo_id}`);
      const button = document.getElementById(`button-${archivo_id}`);

      checker.checked = !checker.checked;

      if (!checker.checked) {
        button.classList.remove("btn-secondary")
        button.classList.add("btn-outline-danger")
        field.classList.remove("archivo-eliminado");
        
    } else {
        button.classList.remove("btn-outline-danger")
        button.classList.add("btn-secondary")
        field.classList.add("archivo-eliminado");
        
    }
  }

</script>

{% endblock %}