admin/src/web/controllers/cobro.py
from datetime import datetime
from flask import flash, redirect, render_template, request, url_for
from flask import session, abort
from core import equipo, pago, cobro, jya
from flask import Blueprint
from web.helpers.auth import check_permission, is_authenticated
import unicodedata

bprint = Blueprint("cobro", __name__, url_prefix="/cobro")


@bprint.get("/")
def index():
    """Página principal que muestra la lista de cobros con paginación, filtro por fechas"""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_index"):
        return abort(403)
    amount_per_page = 10
    try:
        page = int(request.args.get("pag", "1"))
        order = request.args.get("order", "desc")
        medios = request.args.getlist("medioDePago")
        todosLosMedios = cobro.list_medio_de_pago()

        fecha_min = request.args.get("fechamin", "")

        if fecha_min:
            fecha_min = fecha_min.split(" ")[0]
            fecha_min = datetime.strptime(fecha_min, "%Y-%m-%d")
        else:
            fecha_min = datetime.min

        fecha_max = request.args.get("fechamax", "")
        if fecha_max:
            fecha_max = fecha_max.split(" ")[0]
            fecha_max = datetime.strptime(fecha_max, "%Y-%m-%d")
        else:
            fecha_max = datetime.max

        query = request.args.get("query", "")

        cobros = cobro.list_cobros_page(
            amount_per_page, page, fecha_min, fecha_max, order, query, medios
        )
        total = cobro.get_total(fecha_min, fecha_max)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect("/")

    return render_template(
        "cobro/index.html",
        cobros=cobros,
        pag=page,
        page_amount=(total + amount_per_page - 1) // amount_per_page,
        fecha_min=("" if fecha_min == datetime.min else fecha_min),
        fecha_max=("" if fecha_max == datetime.max else fecha_max),
        order=order,
        query=query,
        medios=medios,
        todosLosMedios=todosLosMedios,
    )


@bprint.get("/<id>")
def get_info(id):
    """Muestra la información detallada de un cobro específico."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_get_info"):
        return abort(403)
    try:
        chosen_cobro = cobro.get_one(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("cobro.index"))

    return render_template("cobro/cobro_info.html", info=chosen_cobro)


@bprint.get("<id>/edit")
def enter_edit(id):
    """Permite editar un cobro existente, cargando los datos actuales del cobro."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_enter_edit"):
        return abort(403)
    try:
        chosen_cobro = cobro.get_one(id)

        amount_per_page = 5

        page = int(request.args.get("pag", "1"))

        observaciones = request.args.get("observaciones", chosen_cobro.observaciones)
        monto = request.args.get("monto", chosen_cobro.monto)
        fecha = request.args.get("fecha", chosen_cobro.fecha.strftime("%Y-%m-%d"))
        page_amount = amount_per_page

        empleados = equipo.list_equipos_page(page=page, amount_per_page=amount_per_page)
        total_empleados = equipo.get_total()
        page_amount = (total_empleados + amount_per_page - 1) // amount_per_page

        total_jyas = jya.get_total_jinetes_amazonas()
        page_amount_jya = (total_jyas + amount_per_page - 1) // amount_per_page
        jyas = jya.list_jinetes_amazonas_page(
            query="", page=page, amount_per_page=amount_per_page, order="asc", by=""
        )

        medios = cobro.list_medio_de_pago()
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("cobro.get_one", id=id))

    return render_template(
        "cobro/cobro_editing.html",
        info=chosen_cobro,
        pag=page,
        page_amount=page_amount,
        page_amount_jya=page_amount_jya,
        observaciones=observaciones,
        monto=monto,
        fecha=fecha,
        jyas=jyas,
        empleados=empleados,
        medios=medios,
    )


@bprint.post("<id>/edit")
def save_edit(id):
    """Guarda los cambios realizados a un cobro existente."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_save_edit"):
        return abort(403)
    try:

        try:
            chosen_medio = request.form["chosen-medio"]
        except:
            flash("No se seleccionó un medio de pago", "danger")
            return redirect(url_for("cobro"))

        new_data = {
            "observaciones": request.form["observaciones"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "jya": jya.get_jinete_amazona(request.form["chosen-jya"]),
            "equipo": equipo.get_one(request.form["chosen-equipo"]),
            "medio_pago": cobro.get_one_medio(chosen_medio),
        }

        edited_cobro = cobro.edit(id, new_data)

    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("cobro.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("cobro/cobro_info.html", info=edited_cobro)


@bprint.post("/<id>/borrar")
def delete(id):
    """Elimina un cobro por su ID."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_delete"):
        return abort(403)
    try:
        cobro.delete_cobro(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("get_info", id=id))

    flash("Cobro borrado con éxito", "success")
    return redirect(url_for("cobro.index"))


@bprint.get("/agregar")
def enter_add():
    """Permite agregar un nuevo cobro, mostrando un formulario para ingresar los datos."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_enter_add"):
        return abort(403)

    empleados = equipo.list_equipos_apellido_asc()

    jyas = jya.list_jinetes_amazonas_apellido_asc()

    medios = cobro.list_medio_de_pago()

    observaciones = request.args.get("observaciones", "")
    monto = request.args.get("monto", "")
    fecha = request.args.get("fecha", "")

    return render_template(
        "cobro/cobro_adding.html",
        jyas=jyas,
        empleados=empleados,
        observaciones=observaciones,
        monto=monto,
        fecha=fecha,
        medios=medios,
    )


@bprint.post("/agregar")
def add():
    """Crea un nuevo cobro basado en los datos ingresados en el formulario."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_add"):
        return abort(403)
    try:

        try:
            chosen_jya = request.form["chosen-jya"]
        except:
            flash("No se seleccionó un Jinetes y Amazonas", "danger")
            return redirect(url_for("cobro.enter_add"))
        
        try:
            chosen_equipo = request.form["chosen-equipo"]
        except:
            flash("No se seleccionó un cobrador", "danger")
            return redirect(url_for("cobro.enter_add"))
        
        try:
            chosen_medio = request.form["chosen-medio"]
        except:
            flash("No se seleccionó un medio de pago", "danger")
            return redirect(url_for("cobro.enter_add"))
        

        new_data = {
            "observaciones": request.form["observaciones"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "jya": jya.get_jinete_amazona(chosen_jya),
            "equipo": equipo.get_one(chosen_equipo),
            "medio_pago": cobro.get_one_medio(chosen_medio),
        }

        new_cobro = cobro.create_cobro(**new_data)

    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("cobro.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("cobro/cobro_info.html", info=new_cobro)


@bprint.get("/<id>/<endeudado>")
def set_endeudado(id, endeudado):
    """
    Esta función setea el valor de tiene_deuda del jinete y amazonas
    del cobro con el id pasado por parámetro con el valor del parámetro endeudado
    (solo puede ser booleano)
    """

    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "cobro_set_endeudado"):
        return abort(403)

    try:
        if endeudado == "True":
            endeudado = True
        if endeudado == "False":
            endeudado = False
        chosen_cobro = cobro.get_one(id)
        chosen_jya = jya.set_jinete_amazona_deuda(chosen_cobro.jya.id, endeudado)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("cobro.index"))

    return render_template("cobro/cobro_info.html", info=chosen_cobro)

admin/src/web/templates/cobro/cobro_adding.html
{% extends "layout.html" %} {% block title %} Agregando un cobro {% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<div class="container">
  {% include "cobro/components/messages.html" %}
  <form
    id="add-form"
    class="needs-validation"
    novalidate
    action="{{url_for('cobro.add')}}"
    method="POST"
  >
    <div class="row">
        <div class="col">
          <div class="row mb-5">
            <h2 class="equipo-profile-title text-secondary">
              Observaciones
            </h2>
            <div class="input-group">
              <textarea id="desc-id" class="form-control" name="observaciones" aria-label="With textarea">{{ observaciones }}</textarea>
              <div class="invalid-feedback">
                Ingrese observaciones
              </div>
            </div>
          </div>
          <div class="row">
            <h2 class="equipo-profile-title text-secondary">Datos</h2>
            <ul class="list-unstyled mb-1-9">
              <li class="mb-2 mb-xl-3 display-28">
                  <span class="display-26 text-primary me-2 font-weight-600"
                    >Monto:</span
                  >
                  <div class="input-group">
                      <span class="input-group-text" id="basic-addon1">$</span>
                      <input value="{{ monto }}" id="monto-id" name="monto" class="form-control" required pattern="^(?!0+(\.0+)?$)(\d{1,10}(\.\d{1,2})?)$">
                      <div class="invalid-feedback">
                        Ingrese un monto.
                      </div>
                  </div>
                </li>
                <li class="mb-2 mb-xl-3 display-28">
                  <span class="display-26 text-primary me-2 font-weight-600"
                    >Fecha de cobro:</span
                  >
                  <input value="{{fecha}}" type="date" id="fecha-id" name="fecha" class="form-control" required>
                  <div class="invalid-feedback">
                    Ingrese una fecha.
                  </div>
                </li>
            </ul>
          </div>

          <div class="row mb-5" id="medio-container">
            <div class="col">
              <h2 class="equipo-profile-title text-secondary">Medio de Pago</h2>
            </div>
            <ul class="list-group list-unstyled container">
                {%for medio in medios%}
                <div class="d-flex align-items-center">
                  <input value="{{medio.id}}" class="" type="radio" name="chosen-medio" id="radio-medio-{{medio.id}}">
                  <label class="form-control ms-2" for="radio-medio-{{medio.id}}">
                    {{medio.name}}
                  </label>
                </div>
                {%endfor%}
            </ul>
        </div>
          <div class="row mb-5" id="jya-container">
              <div class="col">
                <h2 class="equipo-profile-title text-secondary">Jinetes y Amazonas</h2>
              </div>
                <div class="mb-3">
                  <label for="dropdown1" class="form-label">Selecciona un Jinete y Amazonas</label>
                  <select class="form-select select2" id="jya_elegido" name="chosen-jya" required>
                    <option value="" selected disabled>Seleccionar JyA...</option>
                    {%for persona in jyas%}
                      <option value="{{persona.id}}">{{persona.apellido}}, {{persona.nombre}}</option>
                    {%endfor%}
                  </select>
                </div>
              <div class="row mb-5" id="equipo-container">
                <div class="col">
                  <h2 class="equipo-profile-title text-secondary">Empleado</h2>
                </div>
                <div class="mb-3">
                  <label for="dropdown2" class="form-label">Selecciona un empleado que cobrará</label>
                  <select class="form-select select2" id="dropdown2" name="chosen-equipo" required>
                    <option value="" selected disabled>Seleccionar Empleado...</option>
                    {%for persona in empleados%}
                      <option value="{{persona.id}}">{{persona.apellido}}, {{persona.nombre}}</option>
                    {%endfor%}
                  </select>
                </div>
              </div>
          </div>
        <div class="col-4 d-flex justify-content-end align-items-start">
          <button
            class="btn btn-outline-primary mx-2 align-self-start"
            type="submit"
          >
            Guardar
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy" viewBox="0 0 16 16">
              <path d="M11 2H9v3h2z"/>
              <path d="M1.5 0h11.586a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13A1.5 1.5 0 0 1 1.5 0M1 1.5v13a.5.5 0 0 0 .5.5H2v-4.5A1.5 1.5 0 0 1 3.5 9h9a1.5 1.5 0 0 1 1.5 1.5V15h.5a.5.5 0 0 0 .5-.5V2.914a.5.5 0 0 0-.146-.353l-1.415-1.415A.5.5 0 0 0 13.086 1H13v4.5A1.5 1.5 0 0 1 11.5 7h-7A1.5 1.5 0 0 1 3 5.5V1H1.5a.5.5 0 0 0-.5.5m3 4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V1H4zM3 15h10v-4.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5z"/>
            </svg>
          </button>
          <a class="btn btn-outline-secondary mx-2 align-self-start" onclick=window.location.href="{{ url_for('cobro.index') }}";>
            Cancelar
          </a>
        </div>
      </div>
  </form>
</div>

<script>
  function toggleBeneficiario() {
  }

  toggleBeneficiario();



  function validateForm(){
    'use strict'

    const form = document.getElementById("add-form")
    const beneficiarios = document.querySelectorAll('input[name="chosen-beneficiario"]');
    let beneficiarioSeleccionado = false;

  
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)

    
  }

  validateForm();
  

</script>

<!-- Incluye Bootstrap JS y Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
        
<!-- Incluye jQuery y Select2 JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock %}

admin/src/web/templates/cobro/cobro_editing.html
{% extends "layout.html" %} {% block title %} Editando un cobro {% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container">
  {% include "cobro/components/messages.html" %}
  <form
    id="edit-form"
    class="needs-validation"
    novalidate
    action="{{url_for('cobro.save_edit', id=info.id)}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="row">
      <div class="col">
        <div class="row mb-5">
          <h2 class="equipo-profile-title text-secondary">
            Observaciones
          </h2>
          <div class="input-group">
            <textarea class="form-control" name="observaciones" id="observaciones-id" aria-label="With textarea" required>{{observaciones}}</textarea>
            <div class="invalid-feedback">
              Ingrese observaciones
            </div>
          </div>
        </div>
        <div class="row">
          <h2 class="equipo-profile-title text-secondary">Datos</h2>
          <ul class="list-unstyled mb-1-9">
            <li class="mb-2 mb-xl-3 display-28">
                <span class="display-26 text-primary me-2 font-weight-600"
                  >Monto:</span
                >
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon1">$</span>
                    <input name="monto" id="monto-id" class="form-control" value="{{ monto }}" required pattern="^(?!0+(\.0+)?$)(\d{1,10}(\.\d{1,2})?)$">
                    <div class="invalid-feedback">
                      Ingrese un monto.
                    </div>
                </div>
              </li>
              <li class="mb-2 mb-xl-3 display-28">
                <span class="display-26 text-primary me-2 font-weight-600"
                  >Fecha de cobro:</span
                >
                <input type="date" name="fecha" id="fecha-id" class="form-control" value="{{ fecha }}" required>
                <div class="invalid-feedback">
                  Ingrese una fecha.
                </div>
              </li>
          </ul>
        </div>
        <div class="row" id="jya-container">
            <div class="col">
              <h2 class="equipo-profile-title text-secondary">Jinetes y Amazonas</h2>
            </div>
            <div class="col-auto">
              {%include 'cobro/components/cobro_pagination_edit.html'%}
            </div>
            <ul class="list-group list-unstyled container">
                {%for persona in jyas%}
                <div class="form-check d-flex align-items-center">
                  <input value="{{persona.id}}" {%if info.jya.id == persona.id %}checked {%endif%} class="form-check-input" type="radio" name="chosen-jya" id="radio-jya-{{persona.id}}">
                  <label class="form-check-label form-control ms-2" for="radio-jya-{{persona.id}}">
                    {{persona.nombre}} {{persona.apellido}}
                  </label>
                </div>
                {%endfor%}
            </ul>
        </div>
        <div class="row" id="equipo-container">
          <div class="col">
            <h2 class="equipo-profile-title text-secondary">Equipo</h2>
          </div>
          <div class="col-auto">
            {%include 'cobro/components/cobro_pagination_edit.html'%}
          </div>
          <ul class="list-group list-unstyled container">
              {%for persona in empleados%}
              <div class="form-check d-flex align-items-center">
                <input value="{{persona.id}}" {%if info.equipo.id == persona.id %}checked {%endif%} class="form-check-input" type="radio" name="chosen-equipo" id="radio-equipo-{{persona.id}}">
                <label class="form-check-label form-control ms-2" for="radio-equipo-{{persona.id}}">
                  {{persona.nombre}} {{persona.apellido}}
                </label>
              </div>
              {%endfor%}
          </ul>
      </div>
      <div class="row" id="medio-container">
        <div class="col">
          <h2 class="equipo-profile-title text-secondary">Medio de Pago</h2>
        </div>
        <ul class="list-group list-unstyled container">
            {%for medio in medios%}
            <div class="d-flex align-items-center">
              <input value="{{medio.id}}" {%if info.medio_pago.id == medio.id %}checked {%endif%} class="" type="radio" name="chosen-medio" id="radio-medio-{{medio.id}}">
              <label class="form-control ms-2" for="radio-medio-{{medio.id}}">
                {{medio.name}}
              </label>
            </div>
            {%endfor%}
        </ul>
    </div>
        
      </div>
      <div class="col-4 d-flex justify-content-end align-items-start">
        <button
          class="btn btn-outline-primary mx-2 align-self-start"
          type="submit"
        >
          Guardar
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy" viewBox="0 0 16 16">
            <path d="M11 2H9v3h2z"/>
            <path d="M1.5 0h11.586a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13A1.5 1.5 0 0 1 1.5 0M1 1.5v13a.5.5 0 0 0 .5.5H2v-4.5A1.5 1.5 0 0 1 3.5 9h9a1.5 1.5 0 0 1 1.5 1.5V15h.5a.5.5 0 0 0 .5-.5V2.914a.5.5 0 0 0-.146-.353l-1.415-1.415A.5.5 0 0 0 13.086 1H13v4.5A1.5 1.5 0 0 1 11.5 7h-7A1.5 1.5 0 0 1 3 5.5V1H1.5a.5.5 0 0 0-.5.5m3 4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V1H4zM3 15h10v-4.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5z"/>
          </svg>
        </button>
        <a class="btn btn-outline-secondary mx-2 align-self-start" onclick=window.location.href="{{ url_for('cobro.get_info', id=info.id) }}";>
          Cancelar
        </a>
      </div>
    </div>
  </form>
</div>

<script>
  function toggleBeneficiario() {
  }



  function validateForm(){
    'use strict'

    const form = document.getElementById("edit-form")
  
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)

    
  }

  validateForm();
  function eliminarArchivo(archivo_id){
      const field = document.getElementById(`archivo-field-${archivo_id}`);
      const checker = document.getElementById(`input-check-${archivo_id}`);
      const button = document.getElementById(`button-${archivo_id}`);

      checker.checked = !checker.checked;

      if (!checker.checked) {
        button.classList.remove("btn-secondary")
        button.classList.add("btn-outline-danger")
        field.classList.remove("archivo-eliminado");
        
    } else {
        button.classList.remove("btn-outline-danger")
        button.classList.add("btn-secondary")
        field.classList.add("archivo-eliminado");
        
    }
  }

</script>

{% endblock %}

admin/src/web/templates/cobro/index.html
{% extends "layout.html" %} {% block title %} Cobros {% endblock %} {% block head
    %} {{ super() }} {% endblock %} {% block content %}
    <main role="main" class="container">
      {% include "cobro/components/messages.html" %}
      <div class="content-body">
        <!-- TITULO -->
        <div class="row align-items-center justify-content-start">
          <div class="col-auto">
            <h1>cobros</h1>
          </div>
        </div>
    
        <!-- BARRA DE BUSQUEDA -->
        {% include 'cobro/components/cobro_searchbar.html'%}
    
        <!-- TABLA CON ELEMENTOS-->
        {% if page_amount > 0 %} {% include "cobro/components/cobro_table.html" %}
        <!-- TABLA SIN ELEMENTOS -->
        {% else %}
        <div class="row container text-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            fill="currentColor"
            class="bi bi-clipboard-minus"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M5.5 9.5A.5.5 0 0 1 6 9h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"
            />
            <path
              d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"
            />
            <path
              d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"
            />
          </svg>
          <h4>No se encontraron cobros</h4>
        </div>
        {% endif %}
      </div>
    </main>
    {% endblock %}
    