admin/src/web/controllers/jya.py
from os import fstat
from flask import render_template, request, url_for, redirect, current_app
from core import (
    equipo,
    jya,
    situacionPrevisional,
    trabajo,
    institucion,
    parienteTutor,
    ecuestre,
)
from core.equipo import Equipo
from core.ecuestre import Ecuestre
from flask import Blueprint
from flask import flash
from flask import session, abort
from web.helpers.auth import check_permission, is_authenticated

bprint = Blueprint("jya", __name__, url_prefix="/jya")


@bprint.get("/")
def index():
    """
    Función que muestra una lista paginada de Jinetes/Amazonas y permite realizar una búsqueda.
    Parameters: Ninguno (Los parámetros de búsqueda, orden y paginación se obtienen de la query de la URL).
    Returns:
        - Si el usuario no está autenticado o no tiene permiso, aborta con los códigos 401 o 403 respectivamente.
        - Si tiene permisos, renderiza la plantilla 'jya/index.html' mostrando los Jinetes/Amazonas filtrados y paginados.
    """

    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "jya_index"):
        return abort(403)
    amount_per_page = 10
    query = request.args.get("query", "")
    order = request.args.get("order", "asc")
    by = request.args.get("by", "")
    page = int(request.args.get("pag", "1"))

    total = jya.get_total_jinetes_amazonas()
    jinetes_amazonas = jya.list_jinetes_amazonas_page(
        query, page, amount_per_page, order, by
    )

    return render_template(
        "jya/index.html",
        jinetes_amazonas=jinetes_amazonas,
        parametro=query,
        order=order,
        by=by,
        pag=page,
        page_amount=(total + amount_per_page - 1) // amount_per_page,
    )


@bprint.get("/<id>")
def get_profile(id):
    """
    Función que muestra el perfil de un Jinete/Amazona por su ID.
    Parameters:
        id (int): El ID del Jinete/Amazona a mostrar.
    Returns:
        - Si el usuario no está autenticado o no tiene permiso, aborta con los códigos 401 o 403 respectivamente.
        - Si el Jinete/Amazona con el ID proporcionado no existe, muestra un mensaje de error y redirige al índice.
        - Si tiene permisos y el Jinete/Amazona es válido, renderiza la plantilla 'jya/profile.html' con la información correspondiente.
    """
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "jya_get_profile"):
        return abort(403)
    try:
        chosen_jinete_amazona = jya.get_jinete_amazona(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("jya.index"))

    return render_template("jya/profile.html", info=chosen_jinete_amazona)


@bprint.get("/agregar")
def enter_add():
    """
    Función que muestra el formulario para agregar un nuevo Jinete/Amazona.
    Parameters: Ninguno.
    Returns:
        - Si el usuario no está autenticado o no tiene permiso, aborta con los códigos 401 o 403 respectivamente.
        - Si tiene permisos, renderiza la plantilla 'jya/add_jya.html' con las listas de equipos y ecuestres.
    """
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "jya_enter_add"):
        return abort(403)
    equipos = Equipo.query.all()
    ecuestres = Ecuestre.query.all()
    return render_template("jya/add_jya.html", equipos=equipos, ecuestres=ecuestres)


@bprint.post("/agregar")
def add_jya():
    """
    Función para agregar un nuevo Jinete/Amazona junto con su situación previsional,
        institución escolar, responsable (pariente/tutor) y trabajo.
    Parameters: Ninguno (Los parámetros se obtienen del formulario de la solicitud POST).
    Returns:
        - Si el usuario no está autenticado o no tiene permiso, aborta con los códigos 401 o 403 respectivamente.
        - Si se crea exitosamente el Jinete/Amazona junto con sus relaciones, redirige al perfil del Jinete/Amazona con un mensaje de éxito.
        - Si ocurre algún error durante la creación, muestra un mensaje de error y redirige al índice.
    """
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "jya_add_jya"):
        return abort(403)
    new_data = {
        "nombre": request.form["nombre"].capitalize(),
        "apellido": request.form["apellido"].capitalize(),
        "dni": request.form["dni"],
        "edad": request.form["edad"],
        "fecha_nacimiento": request.form["fecha_nacimiento"],
        "lugar_nacimiento": request.form["lugar_nacimiento"],
        "domicilio_actual": request.form["domicilio_actual"],
        "telefono_actual": request.form["telefono_actual"],
        "contacto_emergencia": request.form["contacto_emergencia"],
        "tel": request.form["tel"],
        "becado": str_to_bool(request.form["becado"]),
        "porcentaje_beca": request.form["porcentaje_beca"],
        "profesionales_atienden": request.form["profesionales_atienden"],
        "certificado_discapacidad": str_to_bool(
            request.form["certificado_discapacidad"]
        ),
        "asignacion_familiar": str_to_bool(request.form["asignacion_familiar"]),
        "tipo_asignacion_familiar": request.form["tipo_asignacion_familiar"],
        "beneficiario_pension": str_to_bool(request.form["beneficiario_pension"]),
        "beneficiario_pension_tipo": request.form["beneficiario_pension_tipo"],
        "discapacidad": request.form["discapacidad"],
        "otra_discapacidad": request.form["otra_discapacidad"],
        "tipo_discapacidad": request.form["tipo_discapacidad"],
    }

    try:
        new_jinete_amazona = jya.create_jinetes_amazonas(**new_data)

        datos_situacion_previsional = {
            "obra_social": request.form["obra_social"],
            "nroafiliado": request.form["nroafiliado"],
            "curatela": str_to_bool(request.form["curatela"]),
            "observaciones": request.form["observaciones"],
        }

        new_situacion_previsional = situacionPrevisional.create_situacion_previsional(
            **datos_situacion_previsional
        )
        jya.assing_situacion_previsional(new_jinete_amazona, new_situacion_previsional)

        datos_institucion_escolar = {
            "nombre": request.form["nombre_institucion"],
            "direccion": request.form["direccion"],
            "telefono": request.form["telefono_institucion"],
            "grado_actual": request.form["grado_actual"],
            "observaciones": request.form["observaciones_institucion"],
        }

        new_institucion_escolar = institucion.create_institucion_escolar(
            **datos_institucion_escolar
        )
        jya.assing_institucion_escolar(new_jinete_amazona, new_institucion_escolar)

        datos_responsable = {
            "parentesco": request.form["parentesco"],
            "nombre": request.form["nombre_parentesco"],
            "apellido": request.form["apellido_parentesco"],
            "dni": request.form["dni_parentesco"],
            "domicilio_actual": request.form["domicilio_actual_parentesco"],
            "celular_actual": request.form["celular_actual_parentesco"],
            "email": request.form["email_parentesco"],
            "nivel_escolaridad": request.form["nivel_escolaridad_parentesco"],
            "actividad_ocupacion": request.form["actividad_ocupacion_parentesco"],
        }

        new_responsable = parienteTutor.create_parentesco_tutor(**datos_responsable)
        jya.assing_parentesco_tutor(new_jinete_amazona, new_responsable)

        datos_trabajo = {
            "propuestra_trabajo_institucional": request.form[
                "propuestra_trabajo_institucional"
            ],
            "condicion": request.form["condicion_trabajo"],
            "sede": request.form["sede_trabajo"],
            "lunes": str_to_bool(request.form["lunes"]),
            "martes": str_to_bool(request.form["martes"]),
            "miercoles": str_to_bool(request.form["miercoles"]),
            "jueves": str_to_bool(request.form["jueves"]),
            "viernes": str_to_bool(request.form["viernes"]),
            "sabado": str_to_bool(request.form["sabado"]),
            "domingo": str_to_bool(request.form["domingo"]),
        }

        new_trabajo = trabajo.create_trabajo(**datos_trabajo)

        try:

            profesor_terapeuta_id = int(request.form["profesor_terapeuta_id"])
            conductor_id = int(request.form["conductor_id"])
            auxiliar_pista_id = int(request.form["auxiliar_pista_id"])
            caballo_id = int(request.form["caballo_id"])

            if profesor_terapeuta_id:
                profesor_terapeuta_asignado = equipo.get_one(profesor_terapeuta_id)
                if profesor_terapeuta_asignado:
                    trabajo.assing_profesor(new_trabajo, profesor_terapeuta_asignado)
                else:
                    flash("Profesor no encontrado", "warning")
                    return redirect(url_for("jya.index"))

            if conductor_id:
                conductor_asignado = equipo.get_one(conductor_id)
                if conductor_asignado:
                    trabajo.assing_conductor(new_trabajo, conductor_asignado)
                else:
                    flash("Conductor no encontrado", "warning")
                    return redirect(url_for("jya.index"))

            if auxiliar_pista_id:
                auxiliar_pista_asignado = equipo.get_one(auxiliar_pista_id)
                if auxiliar_pista_asignado:
                    trabajo.assing_auxiliar_pista(new_trabajo, auxiliar_pista_asignado)
                else:
                    flash("Auxiliar pista no encontrado", "warning")
                    return redirect(url_for("jya.index"))

            if caballo_id:
                caballo_asignado = ecuestre.get_ecuestre(caballo_id)
                if caballo_asignado:
                    trabajo.assing_caballo(new_trabajo, caballo_asignado)
                else:

admin/src/web/controllers/pago.py
from datetime import datetime
from flask import flash, redirect, render_template, request, url_for
from flask import session, abort
from core import equipo, pago
from flask import Blueprint
from web.helpers.auth import check_permission, is_authenticated

bprint = Blueprint("pago", __name__, url_prefix="/pago")


@bprint.get("/")
def index():
    """Página principal que muestra la lista de pagos con paginación, filtro por fechas y tipos de pago."""
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_index"):
        return abort(403)
    amount_per_page = 10
    try:
        page = int(request.args.get("pag", "1"))
        order = request.args.get("order", "desc")
        tipos = request.args.getlist("tipopago")

        fecha_min = request.args.get("fechamin", "")

        if fecha_min:
            fecha_min = fecha_min.split(" ")[0]
            fecha_min = datetime.strptime(fecha_min, "%Y-%m-%d")
        else:
            fecha_min = datetime.min

        fecha_max = request.args.get("fechamax", "")
        if fecha_max:
            fecha_max = fecha_max.split(" ")[0]
            fecha_max = datetime.strptime(fecha_max, "%Y-%m-%d")
        else:
            fecha_max = datetime.max

        pagos = pago.list_pagos_page(
            amount_per_page, page, fecha_min, fecha_max, tipos, order
        )
        total = pago.get_total(fecha_min, fecha_max, tipos)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect("/")

    return render_template(
        "pago/index.html",
        pagos=pagos,
        pag=page,
        page_amount=(total + amount_per_page - 1) // amount_per_page,
        tipos=tipos,
        fecha_min=("" if fecha_min == datetime.min else fecha_min),
        fecha_max=("" if fecha_max == datetime.max else fecha_max),
        order=order,
    )


@bprint.get("/<id>")
def get_info(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_get_info"):
        return abort(403)
    """Muestra la información detallada de un pago específico."""
    try:
        chosen_pago = pago.get_one(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.index"))

    return render_template("pago/pago_info.html", info=chosen_pago)


@bprint.get("<id>/edit")
def enter_edit(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_enter_edit"):
        return abort(403)
    """Permite editar un pago existente, cargando los datos actuales del pago."""
    try:
        chosen_pago = pago.get_one(id)

        amount_per_page = 5

        page = int(request.args.get("pag", "1"))

        desc = request.args.get("desc", chosen_pago.desc)
        monto = request.args.get("monto", chosen_pago.monto)
        fecha = request.args.get("fecha", chosen_pago.fecha.strftime("%Y-%m-%d"))
        tipo = request.args.get("tipo", chosen_pago.tipo)

        empleados = equipo.list_equipos_page(page=page, amount_per_page=amount_per_page)
        total_empleados = equipo.get_total()
        page_amount = (total_empleados + amount_per_page - 1) // amount_per_page
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.get_one", id=id))

    return render_template(
        "pago/pago_editing.html",
        info=chosen_pago,
        empleados=empleados,
        pag=page,
        page_amount=page_amount,
        desc=desc,
        monto=monto,
        fecha=fecha,
        tipo=tipo,
    )


@bprint.post("<id>/edit")
def save_edit(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_save_edit"):
        return abort(403)
    """Guarda los cambios realizados a un pago existente."""
    try:
        new_data = {
            "desc": request.form["desc"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "tipo": request.form["tipo"],
        }

        edited_pago = pago.edit(id, new_data)

        if new_data["tipo"] == "Honorario":
            try:
                new_person_id = request.form["chosen-beneficiario"]
            except:
                flash("No se seleccionó un beneficiario", "danger")
                return redirect(url_for("pago.enter_edit", id=id))
            new_person = equipo.get_one(new_person_id)
            pago.assign_pago(new_person, edited_pago)
        else:
            if edited_pago.beneficiario_id:
                pago.unassign_pago(edited_pago)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("pago/pago_info.html", info=edited_pago)


@bprint.post("/<id>/borrar")
def delete(id):
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_delete"):
        return abort(403)
    """Elimina un pago por su ID."""
    try:
        pago.delete_pago(id)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("get_info", id=id))

    flash("Pago borrado con éxito", "success")
    return redirect(url_for("pago.index"))


@bprint.get("/agregar")
def enter_add():
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_enter_add"):
        return abort(403)
    """Permite agregar un nuevo pago, mostrando un formulario para ingresar los datos."""
    amount_per_page = 5

    page = int(request.args.get("pag", "1"))
    empleados = equipo.list_equipos_page(page=page, amount_per_page=amount_per_page)
    total_empleados = equipo.get_total()
    page_amount = (total_empleados + amount_per_page - 1) // amount_per_page

    desc = request.args.get("desc", "")
    monto = request.args.get("monto", "")
    fecha = request.args.get("fecha", "")
    tipo = request.args.get("tipo", "")

    return render_template(
        "pago/pago_adding.html",
        empleados=empleados,
        pag=page,
        page_amount=page_amount,
        other_page=(True if page > 1 else False),
        desc=desc,
        monto=monto,
        fecha=fecha,
        tipo=tipo,
    )


@bprint.post("/agregar")
def add():
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "pago_add"):
        return abort(403)
    """Crea un nuevo pago basado en los datos ingresados en el formulario."""
    try:
        new_data = {
            "desc": request.form["desc"],
            "monto": request.form["monto"],
            "fecha": request.form["fecha"],
            "tipo": request.form["tipo"],
        }

        new_pago = pago.create_pago(**new_data)

        if new_data["tipo"] == "Honorario":
            try:
                new_person_id = request.form["chosen-beneficiario"]
            except:
                flash("No se seleccionó un beneficiario", "danger")
                return redirect(url_for("pago.enter_edit", id=id))
            new_person = equipo.get_one(new_person_id)
            pago.assign_pago(new_person, new_pago)
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for("pago.enter_edit", id=id))

    flash("Operación realizada con éxito", "success")
    return render_template("pago/pago_info.html", info=new_pago)

admin/src/web/templates/jya/index.html
{% extends "layout.html" %} {% block title %} Lista de Jinete-Amazonas {% endblock %}
{% block head %} {{ super() }} {% endblock %} {% block content %}
<main role="main" class="container">
  {% include "jya/components/messages.html" %}
  <div class="content-body">
    <!-- TITULO -->
    <div class="row align-items-center justify-content-start">
      <div class="col-auto">
        <h1>Lista de Jinete-Amazonas</h1>
      </div>
      <div class="col-auto">
        <button class="btn btn-outline-primary btn-outline-yellow" onclick=window.location.href="{{url_for('jya.enter_add')}}";>Agregar +</button>
      </div>
    </div>

    <!-- BARRA DE BUSQUEDA -->
    {% include "jya/components/searchbar_jya.html" %} {% if page_amount > 0 %}
    <!-- TABLA CON ELEMENTOS-->
    {% include "jya/jya.html" %} {% else %}
    <!-- TABLA SIN ELEMENTOS -->
    <div class="row container text-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        fill="currentColor"
        class="bi bi-clipboard-minus"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M5.5 9.5A.5.5 0 0 1 6 9h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"
        />
        <path
          d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"
        />
        <path
          d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"
        />
      </svg>
      <h4>No existen elementos con el valor ingresado</h4>
    </div>
    {% endif %}
  </div>
</main>
{% endblock %}

admin/src/web/templates/jya/jya.html
<div class="table-responsive">
    {% include "jya/components/order_by.html"%}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">DNI</th>
            <th scope="col">Edad</th>
            <th scope="col">Fecha nacimiento</th>
            <th scope="col">Teléfono actual</th>
            <th scope="col">Becado</th>

          </tr>
        </thead>
        <tbody>
          {% for jin_am in jinetes_amazonas %}
          <tr>
            <td>{{ jin_am.nombre }}</td>
            <td>{{ jin_am.apellido }}</td>
            <td>{{ jin_am.dni }}</td>
            <td>{{ jin_am.edad }}</td>
            <td>{{ jin_am.fecha_nacimiento.strftime('%d/%m/%Y')  }}</td>
            <td>{{ jin_am.telefono_actual  }}</td>
            <td>{{ jin_am.becado  }}</td>
            <td>
              <div class="container ">
                <div class="row">
                  <a
                    class="col-4 btn btn-sm equipo-search-btn"
                    title="Perfil Jinete/Amazona"
                    href="{{ url_for('jya.get_profile', id=jin_am.id) }}"
                  >
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-data-fill" viewBox="0 0 16 16">
                    <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5z"/>
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5zM10 8a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm4-3a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1"/>
                  </svg>
                  </a>
                  <form class="col-4" action="{{url_for('jya.delete', id=jin_am.id)}}" method="POST" onsubmit="return confirm('¿Está seguro que quiere eliminar este jinete/amazona?')">
                    <button class="col btn btn-sm btn-outline-danger" title="Eliminar jinete/amazona" type="submit">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                      </svg>
                    </button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          {% endfor %}
         
        </tbody>
      </table>
    </div>
    <div>
    </div>

admin/src/web/templates/jya/profile_docs.html
{% extends "layout.html" %} {% block title %} Perfil Jinete/Amazona {{info.id}}
{% endblock %} {% block head %} {{ super() }} {% endblock %} {% block content %}

<div class="container">
  {% include "jya/components/messages.html" %}
  <div class="row">
    <div
      class="container bg-secondary d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded"
    >
      <div class="col">
        <h1 class="h2 text-white mb-0">Documentos</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex align-items-center justify-content-end">
      <a
        class="btn btn-link mx-2 align-self-start"
        href="{{url_for('jya.get_profile', id=info.id)}}"
      >
        ◄ Volver
      </a>
      <button
        type="button"
        class="btn btn-primary"
        data-bs-toggle="modal"
        data-bs-target="#exampleModalArchivos"
      >
        Agregar archivo
      </button>

      <!-- Modal -->
      {%include "jya/components/modal_add_archivos.html"%}

      <button
        type="button"
        class="btn btn-outline-yellow mx-2"
        data-bs-toggle="modal"
        data-bs-target="#exampleModalEnlace"
      >
        Agregar enlace
      </button>

      {%include "jya/components/modal_add_enlace.html"%}

      <div class="row">
        <div class="col">
          <h2 class="jya-profile-title text-secondary">Archivos y Enlaces</h2>
          {% if archivos or enlaces %} {%include
          'jya/components/tabla_docs.html'%} {%else%}
          <span class="display-26 text-primary me-2 font-weight-600"
            >No hay documentos asociados a este Jinete/Amazona</span
          >
          {%endif%}
        </div>

        <div class="row">
          <div class="col"></div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>