admin/src/web/controllers/reporte.py
from datetime import datetime
import math
from flask import (
    flash,
    redirect,
    render_template,
    request,
    url_for,
    send_file,
    current_app,
)
from flask import session, abort
from core import jya
from core import cobro
from core import equipo
from core import ecuestre
from core import trabajo
from flask import Blueprint
from web.helpers.auth import check_permission, is_authenticated
import os

bprint = Blueprint("reporte", __name__, url_prefix="/reporte")


@bprint.get("/")
def index():
    if not is_authenticated(session):
        return abort(401)

    if not check_permission(session, "reporte_index"):
        return abort(403)

    data_discapacidades = get_data_discapacidades()
    data_cobros = get_data_cobros()
    data_puestos = get_data_puestos()
    data_responsables = get_data_responsables()
    data_historial = get_data_historial()
    data_antiguedad = get_data_antiguedad()
    data_deudas = get_data_deudas()
    data_propuestas = get_data_propuestas()

    return render_template(
        "reportes/index.html",
        data_discapacidades=data_discapacidades,
        data_cobros=data_cobros,
        data_puestos=data_puestos,
        data_responsables=data_responsables,
        data_historial=data_historial,
        data_antiguedad=data_antiguedad,
        data_deudas=data_deudas,
        data_propuestas=data_propuestas,
    )


def get_data_discapacidades():
    cant_mental = jya.count_discapacidad("Mental")
    cant_motora = jya.count_discapacidad("Motora")
    cant_sensorial = jya.count_discapacidad("Sensorial")
    cant_visceral = jya.count_discapacidad("Visceral")
    cant_sin = jya.count_discapacidad(None)

    labels = [
        f"Mental: {cant_mental}",
        f"Motora: {cant_motora}",
        f"Sensorial: {cant_sensorial}",
        f"Visceral: {cant_visceral}",
        f"N/A: {cant_sin}",
    ]

    return {
        "cants": [cant_mental, cant_motora, cant_sensorial, cant_visceral, cant_sin],
        "labels": labels,
    }


def get_data_cobros():
    monto_por_mes = cobro.amount_per_month()
    mes_actual = datetime.now().month
    totales = [0] * mes_actual

    for i in monto_por_mes:
        mes = int(i["mes"])
        totales[mes - 1] = i["total"]

    return totales


def get_data_puestos():
    cant_por_puesto = equipo.amount_per_puesto()

    puestos = [
        "Administrativo/a",
        "Terapeuta",
        "Conductor",
        "Auxiliar de pista",
        "Herrero",
        "Veterinario",
        "Entrenador de Caballos",
        "Domador",
        "Profesor de Equitación",
        "Docente de Capacitación",
        "Auxiliar de mantenimiento",
        "Otro",
    ]

    # Crear lista de diccionarios con cantidad inicial en 0
    data = [{"puesto": puesto, "cant": 0} for puesto in puestos]

    for i in cant_por_puesto:
        for item in data:
            if item["puesto"] == i["puesto"]:
                item["cant"] = i["cant"]
                break

    return data


def get_data_responsables():
    pros = equipo.get_all()
    pros.sort(key=lambda p: p.ecuestres.count(), reverse=True)

    return pros


def get_data_historial():
    caballos = ecuestre.list_ecuestres()
    caballos.sort(key=lambda c: c.fecha_ingreso, reverse=True)

    return caballos


def get_data_antiguedad():
    fecha_actual = datetime.now()

    empleados = equipo.get_all()
    empleados.sort(key=lambda e: e.fecha_inicio)

    return [
        {
            "info": e,
            "antiguedad": math.floor((fecha_actual - e.fecha_inicio).days / 365),
        }
        for e in empleados
    ]


def get_data_deudas():
    adeudados = jya.list_jinete_amazona_deuda()

    return adeudados


def get_data_propuestas():
    ranking_propuestas = [
        {"nombre": "Hipoterapia", "cant": 0},
        {"nombre": "Monta terapéutica", "cant": 0},
        {"nombre": "Deporte Ecuestre Adaptado", "cant": 0},
        {"nombre": "Actividades recreativas", "cant": 0},
        {"nombre": "Equitación", "cant": 0},
    ]

    for prop in ranking_propuestas:
        prop["cant"] = trabajo.get_propuestas_cant_solicitadas(prop["nombre"])

    return ranking_propuestas


@bprint.get("/download-adeudados")
def download_adeudados():
    adeudados = jya.list_jinete_amazona_deuda()

    if len(adeudados) == 0:
        return "No data to download."

    csv_data = "Nombre,Teléfono,Domicilio\n"
    for adeudado in adeudados:
        csv_data += f'"{adeudado.nombre} {adeudado.apellido}","{adeudado.telefono_actual}","{adeudado.domicilio_actual}"\n'

    base_path = os.path.abspath(os.path.join(current_app.root_path, "../../"))
    file_path = os.path.join(base_path, "static", "adeudados.csv")
    with open(file_path, "w") as csv_file:
        csv_file.write(csv_data)

    return send_file(file_path, as_attachment=True, download_name="adeudados.csv")


@bprint.get("/download-propuestas")
def download_propuestas():
    ranking_propuestas = get_data_propuestas()

    csv_data = "Ranking,Propuesta,Cantidad de jinetes/amazonas\n"

    ranking_propuestas.sort(key=lambda x: x["cant"], reverse=True)

    for index, prop in enumerate(ranking_propuestas, start=1):
        csv_data += f'{index},"{prop["nombre"]}",{prop["cant"]}\n'

    base_path = os.path.abspath(os.path.join(current_app.root_path, "../../"))
    file_path = os.path.join(base_path, "static", "ranking-propuestas.csv")
    with open(file_path, "w") as csv_file:
        csv_file.write(csv_data)

    return send_file(
        file_path, as_attachment=True, download_name="ranking-propuestas.csv"
    )


@bprint.get("/download-historial")
def download_historial():
    caballos = get_data_historial()

    csv_data = "Nombre,Fecha,Sede,Tipo de adquisición\n"

    caballos.sort(key=lambda c: c.fecha_ingreso, reverse=True)

    for caballo in caballos:
        csv_data += f'"{caballo.nombre}","{caballo.fecha_ingreso.strftime('%d/%m/%Y')}","{caballo.sede_asignada}","{caballo.tipo_adquisicion}"\n'

    base_path = os.path.abspath(os.path.join(current_app.root_path, "../../"))
    file_path = os.path.join(base_path, "static", "historial-caballos.csv")

    with open(file_path, "w") as csv_file:
        csv_file.write(csv_data)

    return send_file(
        file_path, as_attachment=True, download_name="historial-caballos.csv"
    )


@bprint.get("/download-antiguedad")
def download_antiguedad():
    empleados = get_data_antiguedad()

    csv_data = "Nombre,Cantidad de años,Fecha de ingreso\n"

    for empleado in empleados:
        csv_data += f'"{empleado["info"].nombre} {empleado["info"].apellido}",{empleado["antiguedad"]},"{empleado["info"].fecha_inicio.strftime("%d/%m/%Y")}"\n'

    base_path = os.path.abspath(os.path.join(current_app.root_path, "../../"))
    file_path = os.path.join(base_path, "static", "antiguedad-empleados.csv")
    with open(file_path, "w") as csv_file:
        csv_file.write(csv_data)

    return send_file(
        file_path, as_attachment=True, download_name="aniguedad-empleados.csv"
    )

admin/src/web/templates/reportes/components/graficoCobros.html
<div class="container">
  <div class="row">
    <div
      id="data-grafico-cobros"
      data-data="{{ data_cobros | tojson | forceescape }}"
    ></div>
    <canvas id="canvas-grafico-cobros"></canvas>
  </div>
</div>

admin/src/web/templates/reportes/components/graficoDiscapacidades.html
<div class="container">
  <div class="row">
    <div
      id="data-grafico-discapacidades"
      data-labels="{{ data_discapacidades.labels | tojson | forceescape }}"
      data-cants="{{ data_discapacidades.cants | tojson }}"
    ></div>
    <canvas id="canvas-grafico-discapacidades"></canvas>
  </div>
</div>

admin/src/web/templates/reportes/components/graficoPuestos.html
<div class="container">
  <div class="row">
    <div
      id="data-grafico-puestos"
      data-data="{{ data_puestos | tojson | forceescape }}"
    ></div>
    <canvas id="canvas-grafico-puestos"></canvas>
  </div>
</div>

admin/src/web/templates/reportes/components/reporteAntiguedad.html
<div class="container">
  <div class="row">
  <div class="col mb-2">
        <button  class="btn btn-outline-yellow" {%if data_antiguedad|length == 0 %}disabled{%endif%} onclick="window.location.href='{{url_for("reporte.download_antiguedad")}}'">Descargar CSV</button>
    </div>
  </div>
  <div class="row">
    <ul class="list-unstyled">
      {% for empleado in data_antiguedad %}
      <li class="mb-3">
        <span class="display-20 text-primary me-2 font-weight-600">
          <button
            class="btn btn-md btn-outline-yellow"
            onclick=window.location.href="{{ url_for('equipo.get_profile', id=empleado.info.id) }}";
          >
            {{empleado.info.nombre}} {{empleado.info.apellido}}
          </button>
          - {{empleado.antiguedad}} años de antigüedad (fecha de ingreso:
          {{empleado.info.fecha_inicio.strftime("%d/%m/%Y")}})
        </span>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

admin/src/web/templates/reportes/components/reporteDeudas.html
<div class="container">
  <div class="row">
    <div class="col">
        <button  class="btn btn-outline-yellow" {%if data_deudas|length == 0 %}disabled{%endif%} onclick="window.location.href='{{url_for("reporte.download_adeudados")}}'">Descargar CSV</button>
    </div>
  </div>
  <div class="row">
    {% if data_deudas|length == 0 %}
    <div class="col justify-content-center">
        <p class="display-20 me-2 font-weight-600 text-center">No hay personas que adeuden pagos</p>
    </div>    
    {% else %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Teléfono</th>
          <th scope="col">Domicilio</th>
        </tr>
      </thead>
      <tbody>
        {% for adeudado in data_deudas %}
        <tr>
          <td>{{adeudado.nombre}} {{adeudado.apellido}}</td>
          <td>{{adeudado.telefono_actual}}</td>
          <td>{{adeudado.domicilio_actual}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

admin/src/web/templates/reportes/components/reporteHistorial.html
<div class="container">
  <div class="row">
  <div class="col">
        <button  class="btn btn-outline-yellow" {%if data_historial|length == 0 %}disabled{%endif%} onclick="window.location.href='{{url_for("reporte.download_historial")}}'">Descargar CSV</button>
    </div>
  </div>

  <div class="row">
    
    <div class="col-md-6">
      <ul class="timeline">
        {% for caballo in data_historial %}
        <li>
          <span class="display-22 text-primary me-2 font-weight-600"
            >{{caballo.fecha_ingreso.strftime('%d/%m/%Y')}}</span
          >
          <p>
            <a href="{{ url_for('ecuestre.get_profile', id=caballo.id) }}"
              >{{caballo.nombre}}</a
            >
            fue {%if caballo.sexo == 'Macho'%}asignado{%else%}asignada{%endif%}
            a la sede {{caballo.sede_asignada}} mediante una
            {{caballo.tipo_adquisicion.lower()}}.
          </p>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

admin/src/web/templates/reportes/components/reportePropuestas.html
<div class="container">
  <div class="row">
    <div class="col">
        <button  class="btn btn-outline-yellow" onclick="window.location.href='{{url_for("reporte.download_propuestas")}}'">Descargar CSV</button>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Ranking</th>
          <th scope="col">Propuesta</th>
          <th scope="col">Cantidad de jinetes/amazonas</th>
        </tr>
      </thead>
      <tbody>
        {% for prop in data_propuestas|sort(attribute='cant', reverse=True) %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{prop.nombre}}</td>
          <td>{{prop.cant}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

admin/src/web/templates/reportes/components/reporteResponsables.html
<div class="container">
  <div class="row">
    <ul class="list-unstyled mb-1-9">
      {% for profesional in data_responsables %}
      <li class="mb-2 mb-xl-3 display-28">
        <button class="btn btn-outline-yellow" onclick=window.location.href="{{ url_for('equipo.get_profile', id=profesional.id) }}";>
          {{profesional.nombre}} {{profesional.apellido}}
        </button>
        <span class="display-20 text-primary me-2 font-weight-600">
            - Cantidad de caballos asignados: {{profesional.ecuestres.count()}}
        </span>
        <ul class="list-unstyled m-3">
          {% if profesional.ecuestres.count() > 0 %}
          {% for caballo in profesional.ecuestres %}
          <li class="m-2">
            <button class="btn btn-sm btn-outline-lblue" onclick=window.location.href="{{ url_for('ecuestre.get_profile', id=caballo.id) }}";>
                {{caballo.nombre}}
          </button></li>
          {% endfor %}
          {% endif %}
        </ul>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>